name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
    
      - name: Build
        run: ./build.sh

      - name: Create release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            out/*
            kmi.sh
          draft: false
